### ISSUE TITLE
Wrong permission of config.php

### ISSUE THREAD

**Issue by mihailstoynov** [robertdebock/ansible-role-moodle#4]
`/var/www/html/moodle/config.php` has wrong permissions:

```
root@moodle:/var/www/html/moodle# ls -la
[...]
-rwxr-xr-x  1 www-data www-data  56947 May  6  2022 config-dist.php
-rw-r-----  1 root     root        736 Jan 24 21:02 config.php
drwxr-xr-x  7 www-data www-data     13 May  6  2022 contentbank
[...]
```

/var/log/apache2/error.log:
```
[Tue Jan 24 22:04:50.365637 2023] [php:warn] [pid 229] [client 10.0.103.2:39360] PHP Warning:  require_once(/var/www/html/moodle/config.php): Failed to open stream: Permission denied in /var/www/html/moodle/index.php on line 30
[Tue Jan 24 22:04:50.365863 2023] [php:error] [pid 229] [client 10.0.103.2:39360] PHP Fatal error:  Uncaught Error: Failed opening required 'config.php' (include_path='.:/usr/share/php') in /var/www/html/moodle/index.php:30\nStack trace:\n#0 {main}\n  thrown in /var/www/html/moodle/index.php on line 30
```

playbook:
```yaml
- import_playbook: .ansible/roles/robertdebock.moodle/molecule/default/prepare.yml
  when: '"moodle" in inventory_hostname'

- hosts: moodle
  tasks:
  - include_role: { name: robertdebock.moodle }
```

requirements.yml:
```yaml
[...]
- src: robertdebock.moodle                                        # for moodle
- src: robertdebock.bootstrap                                     # for moodle
- src: robertdebock.buildtools                                    # for moodle
- src: robertdebock.epel                                          # for moodle
- src: robertdebock.mysql                                         # for moodle
- src: robertdebock.python_pip                                    # for moodle
- src: robertdebock.openssl                                       # for moodle
- src: robertdebock.php                                           # for moodle
- src: robertdebock.selinux                                       # for moodle
- src: robertdebock.httpd                                         # for moodle
- src: robertdebock.cron                                          # for moodle
- src: robertdebock.core_dependencies                             # for moodle
[...]
```

OS: Ubuntu 22.04 (lxc container), latest version of this role as of writing this bug report 

When permissions are fixed, this no longer persists as an issue.
