### ISSUE TITLE
Too few arguments to function default_error_handler()

### ISSUE THREAD

**Issue by mihailstoynov** [robertdebock/ansible-role-moodle#5]
/var/log/apache2/error.log:
```
[Tue Jan 24 22:17:09.159695 2023] [php:error] [pid 227] [client 10.0.103.2:39462] PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught ArgumentCountError: Too few arguments to function default_error_handler(), 4 passed in /var/www/html/moodle/lib/navigationlib.php on line 897 and exactly 5 expected in /var/www/html/moodle/lib/setuplib.php:425\nStack trace:\n#0 /var/www/html/moodle/lib/navigationlib.php(897): default_error_handler()\n#1 /var/www/html/moodle/lib/setup.php(610): require_once('...')\n#2 /var/www/html/moodle/config.php(32): require_once('...')\n#3 /var/www/html/moodle/index.php(30): require_once('...')\n#4 {main} in /var/www/html/moodle/lib/navigationlib.php on line 897
```

playbook:
```yaml
- import_playbook: .ansible/roles/robertdebock.moodle/molecule/default/prepare.yml
  when: '"moodle" in inventory_hostname'

- hosts: moodle
  tasks:
  - include_role: { name: robertdebock.moodle }
```

requirements.yml:
```yaml
[...]
- src: robertdebock.moodle                                        # for moodle
- src: robertdebock.bootstrap                                     # for moodle
- src: robertdebock.buildtools                                    # for moodle
- src: robertdebock.epel                                          # for moodle
- src: robertdebock.mysql                                         # for moodle
- src: robertdebock.python_pip                                    # for moodle
- src: robertdebock.openssl                                       # for moodle
- src: robertdebock.php                                           # for moodle
- src: robertdebock.selinux                                       # for moodle
- src: robertdebock.httpd                                         # for moodle
- src: robertdebock.cron                                          # for moodle
- src: robertdebock.core_dependencies                             # for moodle
[...]
```

OS: Ubuntu 22.04 (lxc container), latest version of this role as of writing this bug report 

Update: [this](https://moodle.org/mod/forum/discuss.php?d=435732&parent=1753481) says that moodle does not support php 8 and yet the installed php is 8:
```
root@hp-moodle:/var/www/html/moodle# php -v
PHP 8.1.2-1ubuntu2.10 (cli) (built: Jan 16 2023 15:19:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.10, Copyright (c), by Zend Technologies
```
